### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by ashalper-usgs** [kleb/nasarb#4]
Any ideas on this error? Running on CentOS 7 Docker container. Thanks much.
```
# funit climate_hru
computing dependencies
/usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:44:in `match': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:44:in `match'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:44:in `block in modules_defined_in'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:43:in `map'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:43:in `modules_defined_in'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:57:in `block in build_dictionary_of_modules'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:56:in `each'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:56:in `build_dictionary_of_modules'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:89:in `build_hash_of_modules_in_files'
        from /usr/local/share/gems/gems/fortran-1.3.0/lib/fortran.rb:31:in `initialize'
        from /usr/local/share/gems/gems/funit-0.12.4/lib/funit/functions.rb:125:in `new'
        from /usr/local/share/gems/gems/funit-0.12.4/lib/funit/functions.rb:125:in `compile_tests'
        from /usr/local/share/gems/gems/funit-0.12.4/lib/funit.rb:42:in `run_tests'
        from /usr/local/share/gems/gems/funit-0.12.4/bin/funit:61:in `<top (required)>'
        from /usr/local/bin/funit:23:in `load'
        from /usr/local/bin/funit:23:in `<main>'
```
```
# gem list funit

*** LOCAL GEMS ***

funit (0.12.4)
# ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

**Comment by kleb** [comment]
Hi,

My guess is non-ASCII characters in the source.  Try something like a cat -v to see special characters?

Regards,
—
Bil
NASA Senior Researcher for Computational Aerothermodynamics


________________________________________

**Comment by ashalper-usgs** [comment]
I eventually figured out this was due to non-ASCII characters in the Fortran source under test. Thanks very much for your help.
